// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grbebiwrazrrjadltmzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyYmViaXdyYXpycmphZGx0bXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMjg0MTYsImV4cCI6MjA3NDgwNDQxNn0.kxDcrpyEVLHonJLB6nGtT1_Z7wIL0f_fgRWBSnx9LHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});